"""add rolltrace and rollstat

Revision ID: 5268ae951178
Revises: 8f9c1f59afad
Create Date: 2026-08-30 12:57:48.161047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5268ae951178'
down_revision: Union[str, Sequence[str], None] = '8f9c1f59afad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rollstat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roll_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('sd', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('inputs_hash', sa.String(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['roll_id'], ['roll.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rollstat', schema=None) as batch_op:
        batch_op.create_index('idx_rollstat_roll_quantity', ['roll_id', 'quantity'], unique=True)
        batch_op.create_index(batch_op.f('ix_rollstat_roll_id'), ['roll_id'], unique=False)

    op.create_table('rolltrace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roll_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('inputs_hash', sa.String(), nullable=True),
    sa.Column('code_hash', sa.String(), nullable=True),
    sa.Column('params_hash', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('n_samples', sa.Integer(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
    sa.ForeignKeyConstraint(['roll_id'], ['roll.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rolltrace', schema=None) as batch_op:
        batch_op.create_index('idx_rolltrace_roll_kind', ['roll_id', 'kind'], unique=True)
        batch_op.create_index(batch_op.f('ix_rolltrace_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rolltrace_roll_id'), ['roll_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rolltrace', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rolltrace_roll_id'))
        batch_op.drop_index(batch_op.f('ix_rolltrace_file_id'))
        batch_op.drop_index('idx_rolltrace_roll_kind')

    op.drop_table('rolltrace')
    with op.batch_alter_table('rollstat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rollstat_roll_id'))
        batch_op.drop_index('idx_rollstat_roll_quantity')

    op.drop_table('rollstat')
    # ### end Alembic commands ###
