"""add source field for events

Revision ID: 8f9c1f59afad
Revises: a84e2dacf6dc
Create Date: 2026-06-03 04:10:52.932340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f9c1f59afad'
down_revision: Union[str, Sequence[str], None] = 'a84e2dacf6dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rollevent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_rollevent_source_id'), ['source_id'], unique=False)
        batch_op.create_foreign_key('fk_rollevent_source_id_file', 'file', ['source_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rollevent', schema=None) as batch_op:
        batch_op.drop_constraint('fk_rollevent_source_id_file', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_rollevent_source_id'))
        batch_op.drop_column('source_id')

    # ### end Alembic commands ###
