"""add file timing columns

Revision ID: a84e2dacf6dc
Revises: 9c2d4f1a7b3c
Create Date: 2026-05-31 17:24:12.098287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a84e2dacf6dc'
down_revision: Union[str, Sequence[str], None] = '9c2d4f1a7b3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.add_column('rollfile', sa.Column('local_start_ms', sa.Integer(), nullable=True))
    op.add_column('rollfile', sa.Column('local_end_ms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rollfile', 'local_end_ms')
    op.drop_column('rollfile', 'local_start_ms')
    op.drop_column('file', 'start_time')
    # ### end Alembic commands ###
