/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RollsChar123RollIdChar125RouteImport } from './routes/rolls.{-$rollId}'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RollsChar123RollIdChar125Route =
  RollsChar123RollIdChar125RouteImport.update({
    id: '/rolls/{-$rollId}',
    path: '/rolls/{-$rollId}',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rolls/{-$rollId}': typeof RollsChar123RollIdChar125Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rolls/{-$rollId}': typeof RollsChar123RollIdChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rolls/{-$rollId}': typeof RollsChar123RollIdChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/rolls/{-$rollId}'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/rolls/{-$rollId}'
  id: '__root__' | '/' | '/rolls/{-$rollId}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RollsChar123RollIdChar125Route: typeof RollsChar123RollIdChar125Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rolls/{-$rollId}': {
      id: '/rolls/{-$rollId}'
      path: '/rolls/{-$rollId}'
      fullPath: '/rolls/{-$rollId}'
      preLoaderRoute: typeof RollsChar123RollIdChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RollsChar123RollIdChar125Route: RollsChar123RollIdChar125Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
