/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RollsRouteImport } from './routes/rolls'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecordingRollIdRouteImport } from './routes/recording.$rollId'

const RollsRoute = RollsRouteImport.update({
  id: '/rolls',
  path: '/rolls',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordingRollIdRoute = RecordingRollIdRouteImport.update({
  id: '/recording/$rollId',
  path: '/recording/$rollId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rolls': typeof RollsRoute
  '/recording/$rollId': typeof RecordingRollIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rolls': typeof RollsRoute
  '/recording/$rollId': typeof RecordingRollIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rolls': typeof RollsRoute
  '/recording/$rollId': typeof RecordingRollIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/rolls' | '/recording/$rollId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/rolls' | '/recording/$rollId'
  id: '__root__' | '/' | '/rolls' | '/recording/$rollId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RollsRoute: typeof RollsRoute
  RecordingRollIdRoute: typeof RecordingRollIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rolls': {
      id: '/rolls'
      path: '/rolls'
      fullPath: '/rolls'
      preLoaderRoute: typeof RollsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recording/$rollId': {
      id: '/recording/$rollId'
      path: '/recording/$rollId'
      fullPath: '/recording/$rollId'
      preLoaderRoute: typeof RecordingRollIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RollsRoute: RollsRoute,
  RecordingRollIdRoute: RecordingRollIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
