/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RollsRouteImport } from './routes/rolls'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RollsIndexRouteImport } from './routes/rolls/index'
import { Route as RollsNewRouteImport } from './routes/rolls/new'
import { Route as RollsRollIdIndexRouteImport } from './routes/rolls/$rollId.index'
import { Route as RollsRollIdRecordingRouteImport } from './routes/rolls/$rollId.recording'
import { Route as RollsRollIdEditRouteImport } from './routes/rolls/$rollId.edit'

const RollsRoute = RollsRouteImport.update({
  id: '/rolls',
  path: '/rolls',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RollsIndexRoute = RollsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RollsRoute,
} as any)
const RollsNewRoute = RollsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => RollsRoute,
} as any)
const RollsRollIdIndexRoute = RollsRollIdIndexRouteImport.update({
  id: '/$rollId/',
  path: '/$rollId/',
  getParentRoute: () => RollsRoute,
} as any)
const RollsRollIdRecordingRoute = RollsRollIdRecordingRouteImport.update({
  id: '/$rollId/recording',
  path: '/$rollId/recording',
  getParentRoute: () => RollsRoute,
} as any)
const RollsRollIdEditRoute = RollsRollIdEditRouteImport.update({
  id: '/$rollId/edit',
  path: '/$rollId/edit',
  getParentRoute: () => RollsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rolls': typeof RollsRouteWithChildren
  '/rolls/new': typeof RollsNewRoute
  '/rolls/': typeof RollsIndexRoute
  '/rolls/$rollId/edit': typeof RollsRollIdEditRoute
  '/rolls/$rollId/recording': typeof RollsRollIdRecordingRoute
  '/rolls/$rollId': typeof RollsRollIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rolls/new': typeof RollsNewRoute
  '/rolls': typeof RollsIndexRoute
  '/rolls/$rollId/edit': typeof RollsRollIdEditRoute
  '/rolls/$rollId/recording': typeof RollsRollIdRecordingRoute
  '/rolls/$rollId': typeof RollsRollIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rolls': typeof RollsRouteWithChildren
  '/rolls/new': typeof RollsNewRoute
  '/rolls/': typeof RollsIndexRoute
  '/rolls/$rollId/edit': typeof RollsRollIdEditRoute
  '/rolls/$rollId/recording': typeof RollsRollIdRecordingRoute
  '/rolls/$rollId/': typeof RollsRollIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/rolls'
    | '/rolls/new'
    | '/rolls/'
    | '/rolls/$rollId/edit'
    | '/rolls/$rollId/recording'
    | '/rolls/$rollId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/rolls/new'
    | '/rolls'
    | '/rolls/$rollId/edit'
    | '/rolls/$rollId/recording'
    | '/rolls/$rollId'
  id:
    | '__root__'
    | '/'
    | '/rolls'
    | '/rolls/new'
    | '/rolls/'
    | '/rolls/$rollId/edit'
    | '/rolls/$rollId/recording'
    | '/rolls/$rollId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RollsRoute: typeof RollsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rolls': {
      id: '/rolls'
      path: '/rolls'
      fullPath: '/rolls'
      preLoaderRoute: typeof RollsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rolls/': {
      id: '/rolls/'
      path: '/'
      fullPath: '/rolls/'
      preLoaderRoute: typeof RollsIndexRouteImport
      parentRoute: typeof RollsRoute
    }
    '/rolls/new': {
      id: '/rolls/new'
      path: '/new'
      fullPath: '/rolls/new'
      preLoaderRoute: typeof RollsNewRouteImport
      parentRoute: typeof RollsRoute
    }
    '/rolls/$rollId/': {
      id: '/rolls/$rollId/'
      path: '/$rollId'
      fullPath: '/rolls/$rollId'
      preLoaderRoute: typeof RollsRollIdIndexRouteImport
      parentRoute: typeof RollsRoute
    }
    '/rolls/$rollId/recording': {
      id: '/rolls/$rollId/recording'
      path: '/$rollId/recording'
      fullPath: '/rolls/$rollId/recording'
      preLoaderRoute: typeof RollsRollIdRecordingRouteImport
      parentRoute: typeof RollsRoute
    }
    '/rolls/$rollId/edit': {
      id: '/rolls/$rollId/edit'
      path: '/$rollId/edit'
      fullPath: '/rolls/$rollId/edit'
      preLoaderRoute: typeof RollsRollIdEditRouteImport
      parentRoute: typeof RollsRoute
    }
  }
}

interface RollsRouteChildren {
  RollsNewRoute: typeof RollsNewRoute
  RollsIndexRoute: typeof RollsIndexRoute
  RollsRollIdEditRoute: typeof RollsRollIdEditRoute
  RollsRollIdRecordingRoute: typeof RollsRollIdRecordingRoute
  RollsRollIdIndexRoute: typeof RollsRollIdIndexRoute
}

const RollsRouteChildren: RollsRouteChildren = {
  RollsNewRoute: RollsNewRoute,
  RollsIndexRoute: RollsIndexRoute,
  RollsRollIdEditRoute: RollsRollIdEditRoute,
  RollsRollIdRecordingRoute: RollsRollIdRecordingRoute,
  RollsRollIdIndexRoute: RollsRollIdIndexRoute,
}

const RollsRouteWithChildren = RollsRoute._addFileChildren(RollsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RollsRoute: RollsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
